from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def build_markdown_report(scenario: dict[str, Any], analysis: dict[str, Any]) -> str:
    title = scenario.get("name", "ChronoNet incident")
    lines = [
        f"# Incident Report — {title}",
        "",
        f"Generated by **ChronoNet** at {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
        "## Executive summary",
        "",
        analysis.get("summary", "No summary available."),
        "",
        f"- Events analyzed: **{analysis.get('event_count', 0)}**",
        f"- Incident duration: **{analysis.get('duration_seconds', 0)} seconds**",
        f"- Affected nodes: **{len(analysis.get('affected_nodes', []))}**",
        f"- Health score: **{analysis.get('health_score', 100)}/100**",
        "",
        "## Root-cause findings",
        "",
    ]

    findings = analysis.get("findings", [])
    if not findings:
        lines.append("No high-confidence finding was produced.")
    for idx, finding in enumerate(findings, 1):
        lines.extend([
            f"### {idx}. {finding['title']}",
            "",
            f"**Confidence:** {finding['confidence']}%  ",
            f"**Severity:** {finding['severity'].upper()}",
            "",
            "Evidence:",
        ])
        lines.extend(f"- {item}" for item in finding.get("evidence", []))
        lines.extend(["", f"Recommendation: {finding.get('recommendation', '')}", ""])

    lines.extend(["## Affected nodes", ""])
    nodes = analysis.get("affected_nodes", [])
    lines.extend(f"- `{node}`" for node in nodes) if nodes else lines.append("None recorded.")
    lines.extend(["", "## Scenario description", "", str(scenario.get("description", "")), ""])
    return "\n".join(lines)
